// <auto-generated />
using System;
using HospitalApp.Model.MyDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220831164445_AppointmentDatesUpdated")]
    partial class AppointmentDatesUpdated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("HospitalApp.Model.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 9, 23, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsTaken = false,
                            PatientId = 0
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 9, 27, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsTaken = false,
                            PatientId = 0
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 8, 30, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsTaken = false,
                            PatientId = 0
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 9, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            IsTaken = false,
                            PatientId = 0
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 10, 2, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsTaken = false,
                            PatientId = 0
                        });
                });

            modelBuilder.Entity("HospitalApp.Model.AppointmentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AppointmentComment")
                        .HasColumnType("longtext");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<double>("DoctorRating")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("AppointmentHistory");
                });

            modelBuilder.Entity("HospitalApp.Model.Users.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Savo",
                            Surname = "Naokmet",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Simo",
                            Surname = "Samardzic",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nikola",
                            Surname = "Kosjerina",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Milorad Miko Messi",
                            Surname = "Medan",
                            Type = 1
                        });
                });

            modelBuilder.Entity("HospitalApp.Model.Users.RegUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RegUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RegUser");
                });

            modelBuilder.Entity("HospitalApp.Model.Users.Admin", b =>
                {
                    b.HasBaseType("HospitalApp.Model.Users.RegUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("HospitalApp.Model.Users.Patient", b =>
                {
                    b.HasBaseType("HospitalApp.Model.Users.RegUser");

                    b.Property<string>("BloodType")
                        .HasColumnType("longtext");

                    b.Property<string>("HealthCard")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsBlockable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
